export default ` edges{
    node{
        availableForSale
        compareAtPriceRange{
            maxVariantPrice{
                amount
                currencyCode
            }
            minVariantPrice{
                amount
                currencyCode
            }
        }
        createdAt
        description
        descriptionHtml
        featuredImage{
            altText
            height
            id
            url
            width
        }
        handle
        id
        images(first:10){
            edges{
                cursor
                node{
                    altText
                    height
                    id
                    url
                    width
                }
                node{
                    altText
                    height
                    id
                    url
                    width
                }
            }
        }
        isGiftCard
        media(first:10){
            edges{
                cursor
                node{
                    __typename
                    alt
                    mediaContentType
                    presentation{
                      
                        id
                    }
                    previewImage{
                        altText
                        height
                        id
                        url
                        width
                    }

                }
            }
        }
       onlineStoreUrl
       priceRange{
           maxVariantPrice{
               amount
               currencyCode
           }
           minVariantPrice{
               amount
               currencyCode
           }
       }
       productType
       publishedAt
       requiresSellingPlan
       seo{
           description
           title
       }
      tags
      title
      totalInventory
      updatedAt
      
      variants(first:10){
          edges{
              cursor
             node {
                  availableForSale
                  barcode
                  compareAtPrice{
                      amount
                      currencyCode
                  }
                  currentlyNotInStock
                  id
                  image{
                      altText
                      height
                      url
                      id
                      width
                  }
                  price{
                      amount
                      currencyCode
                  }
                 weight
                 weightUnit
                 unitPrice{
                     amount
                     currencyCode
                 }
                 unitPriceMeasurement{
                     measuredType
                     quantityUnit
                     referenceUnit
                     referenceValue
                 }
                 title
                 storeAvailability(first:10){
                     pageInfo{
                         endCursor
                         hasNextPage
                         hasPreviousPage
                         startCursor
                     }
                 }

              }
          }
      }

       options{
           id
           name
           values
       }
    }

}
`