import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  container: {
    height: hp(2),
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#e6f0f2',
    flexDirection: 'row',
    paddingHorizontal: wp(6),
  },
  details: {
    flex: 1,
    overflow: 'hidden',
  },
  prDeta: {
    height: hp(4),
    width: wp(35),
  },
  count: {
    right: wp(6),
    height: hp(4),
    width: wp(30),
    paddingHorizontal: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cont: {
    flexDirection: 'row',
    width: '100%',

    justifyContent: 'space-between',
    marginTop: wp(4),
  },
  plus: {
    height: hp(3.6),
    width: hp(3.6),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: wp(0.1),
    borderRadius: wp(2),
  },
  ratting: {
    width: wp(30),
    marginLeft: wp(-8),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: wp(4),
  },
  description: {
    paddingVertical: wp(2),
    marginLeft: wp(7),
    marginTop: wp(4),
  },
  btn: {
    borderWidth: 1,
    width: wp(34),
    left: wp(5),
    height: hp(4.7),
    borderRadius: wp(3),
    backgroundColor: '#0f3a8d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  specification: {
    width: wp(90),
    alignSelf: 'center',
    borderRadius: wp(2),
    backgroundColor: '#f2f5f4',
    paddingHorizontal: wp(5),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: wp(4),
    paddingVertical: wp(2),
  },
  btn2: {
    height: hp(4.5),
    width: hp(5),
    backgroundColor: '#f2f5f4',
    borderRadius: wp(1.5),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 2,
    alignSelf: 'center',
    marginTop: wp(7),
  },

  btn3: {
    height: hp(5.5),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(1),
    backgroundColor: 'green',
  },
  imgcontainer: {
    height: wp(40),
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e6f0f2',
  },
  img: {
    height: '90%',
    width: '90%',
  },
  title: {
    marginTop: wp(1),
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'black',
  },
  cardView: {
    height: hp(25),
    backgroundColor: '#e6f0f2',
    marginVertical: wp(1),
    width: wp(46),
    marginHorizontal: wp(1),
    
  },
  quantity: {
    height: hp(4),
    width: hp(4),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e6f0f2',
    borderRadius: wp(1),
  },
  quantityContainer: {
    flexDirection: 'row',
    height: hp(4.5),
    width: '35%',
    justifyContent: 'space-between',
    alignItems: 'center',

    alignSelf: 'center',
    backgroundColor: '#e6f0f2',
    borderRadius: wp(1),
    paddingHorizontal: wp(2),
    borderWidth: wp(0.1),
    marginTop: wp(1),
    marginRight: wp(3),
  },
  varBtn: {
    height: hp(4),
    width: wp(30),
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginLeft: wp(10),
    borderWidth: wp(0.5),
    flexDirection: 'row',
    paddingHorizontal: wp(3),
  },
  varTitle: {
    fontSize: wp(4),
    color: '#A36B25',
    fontWeight: '600',
    fontStyle: 'italic',
  },
});
