import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  container: {
    height: hp(8),
    width: '100%',
    alignItems: 'center',
    //justifyContent:'center',
    backgroundColor: '#e6f0f2',
    // borderWidth:1

    flexDirection: 'row',
    //justifyContent:'space-between',
    paddingHorizontal: wp(6),
  },
  details: {
    flex: 1,
    // backgroundColor: 'white',
    marginTop: wp(10),
    //borderTopRightRadius: wp(12),
    //borderTopLeftRadius: wp(12),
    // shadowColor: 'black',
    // shadowOffset: {width: -2, height: 4},
    // shadowOpacity: 0.7,
    // shadowRadius: 3,
    // elevation: 2,
    overflow: 'hidden',
  },
  prDeta: {
    borderWidth: wp(0.3),
    height: hp(4),
    width: wp(35),
    marginLeft: wp(5),
    borderRadius: wp(8),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
    //marginTop: wp(8),
  },
  count: {
    //  borderWidth: 1,
    right: wp(6),
    height: hp(4),
    width: wp(30),
    paddingHorizontal: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // marginTop: wp(8),
  },
  cont: {
    flexDirection: 'row',
    width: '100%',
    //  top: wp(7),
    //borderWidth: 1,
    justifyContent: 'space-between',
    marginTop: wp(4),
  },
  plus: {
    height: hp(3.6),
    width: hp(3.6),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: wp(0.1),
    borderRadius: wp(2),
  },
  ratting: {
    // borderWidth:1,
    // top: wp(10),
    width: wp(30),
    marginLeft: wp(8),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: wp(4),
  },
  description: {
    paddingVertical: wp(2),
    marginLeft: wp(7),
    marginTop: wp(4),
  },
  btn: {
    borderWidth: 1,
    //top: wp(22),
    width: wp(34),
    left: wp(5),
    height: hp(4.7),
    borderRadius: wp(3),
    backgroundColor: '#0f3a8d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  specification: {
    width: wp(90),
    alignSelf: 'center',
    // borderWidth:1,
    // top: wp(30),
    paddingVertical: wp(1),
    borderRadius: wp(2),
    backgroundColor: '#f2f5f4',
    paddingHorizontal: wp(5),
    alignItems: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: wp(4),
    //height: hp(6),
    paddingVertical: wp(2),
  },
  btn2: {
    height: hp(4.5),
    width: hp(5),
    backgroundColor: '#f2f5f4',
    borderRadius: wp(1.5),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 2,
  },
  title: {
    fontSize: wp(5),
    textAlign: 'center',
    marginTop: wp(1),
    fontWeight: 'bold',
  },
  btn3: {
    height: hp(5.5),
    width: '100%',
    //borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(1),
    backgroundColor: '#c5c0cf',
  },
  imgcontainer: {
    height: wp(40),
    width: '100%',
    alignSelf: 'center',
    // marginTop: wp(3),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e6f0f2',
  },
  img: {
    height: '90%',
    width: '90%',
  },
  title: {
    marginTop: wp(1),
    alignSelf: 'center',
    fontWeight: 'bold',
    color: 'black',
  },
  cardView: {
    height: hp(25),
    backgroundColor: '#e6f0f2',
    marginVertical: wp(1),
    width: wp(46),
    marginHorizontal: wp(1),
    //borderRadius: wp(2),
    // shadowColor: 'black',
    // shadowOpacity: 0.05,
  },
  quantity: {
    height: hp(4),
    width: hp(4),
    alignItems: 'center',
    // borderWidth: 1,
    justifyContent: 'center',
    backgroundColor: '#e6f0f2',
    borderRadius: wp(1),
  },
  quantityContainer: {
    flexDirection: 'row',
    height: hp(4.5),
    width: '35%',
    justifyContent: 'space-between',
    alignItems: 'center',

    alignSelf: 'center',
    backgroundColor: '#e6f0f2',
    borderRadius: wp(1),
    paddingHorizontal: wp(2),
    borderWidth: wp(0.1),
    marginTop: wp(1),
    marginRight: wp(3),
  },
});
