import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  header: {
    height: hp(7),
    backgroundColor: '#e6f0f2',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(3),
    shadowColor: 'black',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  txt: {
    fontSize: wp(4),
    color: 'grey',
  },
  container: {
    marginVertical: wp(1),
    width: '100%',
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  img: {
    // borderWidth:1,
    height: hp(10),
    width: hp(10),
    marginRight: wp(15),
    borderRadius: hp(5),
  },
  cat: {
    backgroundColor: 'white',
    marginHorizontal: wp(1),
    height: '65%',
    alignSelf: 'center',
    alignItems: 'center',
    // justifyContent:'center',
    paddingHorizontal: wp(2),
    borderRadius: wp(3),
    borderWidth: wp(0.1),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameContainer: {
    height: hp(5),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    paddingRight: wp(7),
    marginTop: wp(2),
  },
  cardContainer: {
    paddingHorizontal: wp(3),
    marginVertical: wp(4),
    justifyContent: 'space-between',
    height: hp(12),
  },
  touchBtn: {
    borderWidth: wp(0.2),
    borderColor: 'grey',
    width: wp(45),
    height: hp(5),
    borderRadius: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: wp(3),
    paddingRight: wp(2),
    backgroundColor: '#f2f5f4',
  },
  listContainer: {
    borderTopWidth: wp(0.2),
    borderColor: 'grey',
    //marginTop:wp(3),
    paddingVertical: wp(2),
    backgroundColor: '#f2f5f4',
    paddingHorizontal: wp(2),
    //alignItems:'center',
    // justifyContent: 'space-between',
    //flexDirection: 'row',
  },
  btn: {
    marginVertical: wp(4),
    height: hp(6),
    width: wp(85),
    alignSelf: 'center',
    borderWidth: wp(0.3),
    borderColor: 'red',
    borderRadius: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  HideView: {
    paddingVertical: wp(3),
    //: 'center',
    width: '58%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: wp(3),
  },
  btn2: {
    borderWidth: wp(0.08),
    height: hp(10),
    width: wp(25),
    borderRadius: wp(3),
    borderColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
